Adds client side channel creation (resolves #11)
JakeNarkizian/sound-send pull request #60
Opened 2016-11-14 05:49 UTC by bluesnowstorm

the code is in the sound send  folder, not the sejaladiti one
the code is in ViewController. this makes it easier to get alerts through, since the httprequest is asyncronous

createChannel doesn't have a unit test, because its asynchronous and i don't know how that would work. the entirety of the asynchronous part is in a function, so hopefully its mitigated.
handleCreateChannelResponse also doesn't have a unit test. i'm not sure how to properly test it honestly. much of its output is on the ui.
showAlert is entirely a ui thing
generateCreateChannelURL and handleCreateChannelResponseCode have unit tests

you can test this code by putting createChannel("test") in viewDidLoad. as it is, an alert should pop up and show "Error 200" since someone owns soundsend.com. 201 is what main.py has as the correct code, which is why it shows "error". changing the baseurl to "sound-send.com" pops up a different error, this time from client side, since that domain doesn't exist. with baseurl pointed the right way, no popups should appear and the channel should be created server side. i wasn't able to test this.

2016-11-14 05:50 UTC, bluesnowstorm commented
@JakeNarkizian please review

2016-11-15 08:33 UTC, nsjake requested changes
@bluesnowstorm please take a look at my comments.

2016-11-15 08:33 UTC, nsjake commented on ios/sound-send/sound-send/ViewController.swift
> +    //these response codes are taken from main.py
Remove this comment, this is internal stuff we dont need this in the code

2016-11-15 08:33 UTC, nsjake commented on ios/sound-send/sound-send/ViewController.swift
> +    let baseurl = "http://www.soundsend.com"
@adgupta @seant2g0 what have you guys been doing for the baseurl variable? I think we should have one variable in a central swift file somewhere and have all uses of it come from that file. Thoughts?

2016-11-15 08:33 UTC, nsjake commented on ios/sound-send/sound-send/ViewController.swift
> +        //this gives a uuid that is random, and static as long as the app is installed. i think.
Remove this comment. This is implied by the variable name uuid which stands for universally unique identifier.

2016-11-15 08:33 UTC, JakeNarkizian commented on ios/sound-send/sound-send/ViewController.swift
> +    var sessioninprogress = false
Remove this variable and all its uses. It's usually a bad idea to introduce state when we don't need it. I don't imagine a use case where the user is allowed to create a channel if a previous one has not been canceled.

2016-11-15 08:33 UTC, JakeNarkizian commented on ios/sound-send/sound-send/ViewController.swift
> +    var sessioninprogress = false
@bluesnowstorm infact I propose a channel class and an optional variable that points to the current channel. This way we can forgo the need for a state variable and instead rely on the power of optionals. have something like:
```
var currentChannel = Channel(...)
```
When a broadcaster cancels a request (this is sort of thinking ahead) we can call the destructor on currentChannel and set it to nil.

2016-11-15 08:33 UTC, JakeNarkizian commented on ios/sound-send/sound-send/ViewController.swift
> +        return baseurl+"/channelManager/createChannel/"+channelname+"/"+uuid
- factor out ```channelManager``` into a variable like ```baseurl```.
- all this stuff should be lowercase

2016-11-15 08:33 UTC, JakeNarkizian commented on ios/sound-send/sound-send/ViewController.swift
> +    //the input channel name, the device uuid, and a layout i got from a random comment in
Remove this comment

2016-11-15 08:33 UTC, JakeNarkizian commented on ios/sound-send/sound-send/ViewController.swift
> +    let channelcreatesuccess = 201
Change to successStatusCode and failureStatusCode

2016-11-15 08:52 UTC, adgupta commented on ios/sound-send/sound-send/ViewController.swift
> +    let baseurl = "http://www.soundsend.com"
We've just been putting them where Arnav has put his in his code. But maybe we could declare it in a class function so it'll be available throughout the project

2016-11-16 00:04 UTC, seant2g0 commented on ios/sound-send/sound-send/ViewController.swift
> +    let baseurl = "http://www.soundsend.com"
Yeah mine is currently in the same format for the base url. We can try Aditi's plan of declaring it as a class function.

2016-11-16 11:02 UTC, nsjake approved these changes

2016-11-16 11:02 UTC, merged